using KplTournament.Web.Models.ViewModels;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace KplTournament.Web.Services
{
    /// <summary>
    /// Renders a completed (or in-progress) match's scorecard as a downloadable PDF.
    /// Uses QuestPDF's free Community license — see Program.cs for the license registration.
    /// </summary>
    public static class ScorecardPdfService
    {
        public static byte[] Generate(ScorecardViewModel vm)
        {
            var teamAName = vm.Match.TeamA?.Name ?? "Team A";
            var teamBName = vm.Match.TeamB?.Name ?? "Team B";

            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(30);
                    page.DefaultTextStyle(x => x.FontSize(10));

                    page.Header().Column(col =>
                    {
                        col.Item().Text($"{teamAName} vs {teamBName}")
                            .FontSize(18).Bold();

                        col.Item().Text(vm.Match.Venue ?? "")
                            .FontSize(10).FontColor(Colors.Grey.Darken1);

                        col.Item().PaddingTop(4).Text(
                            !string.IsNullOrWhiteSpace(vm.Match.ResultText) ? vm.Match.ResultText : vm.Match.Result)
                            .FontSize(11).Bold();

                        col.Item().PaddingTop(2).LineHorizontal(1).LineColor(Colors.Grey.Lighten1);
                    });

                    page.Content().PaddingTop(10).Column(col =>
                    {
                        col.Spacing(14);
                        col.Item().Element(c => RenderInnings(c, vm.Innings1));
                        col.Item().Element(c => RenderInnings(c, vm.Innings2));
                    });

                    page.Footer().AlignCenter().Text(x =>
                    {
                        x.Span("Generated by CricZone Arena — ").FontSize(8).FontColor(Colors.Grey.Medium);
                        x.Span(DateTime.Now.ToString("dd MMM yyyy HH:mm")).FontSize(8).FontColor(Colors.Grey.Medium);
                    });
                });
            });

            return document.GeneratePdf();
        }

        private static void RenderInnings(QuestPDF.Infrastructure.IContainer container, InningsScorecardViewModel innings)
        {
            container.Column(col =>
            {
                col.Spacing(6);

                col.Item().Background(Colors.Grey.Lighten3).Padding(6).Row(row =>
                {
                    row.RelativeItem().Text(innings.BattingTeamName).Bold().FontSize(12);
                    row.AutoItem().Text($"{innings.TotalRuns}-{innings.Wickets} ({innings.Overs} Ov, RR {innings.RunRate:0.00})").Bold();
                });

                if (innings.Batting.Any())
                {
                    col.Item().Text("Batting").Bold().FontSize(10);
                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(c =>
                        {
                            c.RelativeColumn(3);
                            c.RelativeColumn(3);
                            c.RelativeColumn(1);
                            c.RelativeColumn(1);
                            c.RelativeColumn(1);
                            c.RelativeColumn(1);
                            c.RelativeColumn(1);
                        });

                        table.Header(header =>
                        {
                            foreach (var h in new[] { "Batter", "Status", "R", "B", "4s", "6s", "SR" })
                                header.Cell().Element(HeaderCell).Text(h).Bold();
                        });

                        foreach (var b in innings.Batting)
                        {
                            table.Cell().Element(BodyCell).Text(b.PlayerName);
                            table.Cell().Element(BodyCell).Text(b.Status);
                            table.Cell().Element(BodyCell).Text(b.Runs.ToString());
                            table.Cell().Element(BodyCell).Text(b.Balls.ToString());
                            table.Cell().Element(BodyCell).Text(b.Fours.ToString());
                            table.Cell().Element(BodyCell).Text(b.Sixes.ToString());
                            table.Cell().Element(BodyCell).Text(b.StrikeRate.ToString("0.0"));
                        }
                    });
                }

                col.Item().PaddingTop(2).Text(
                    $"Extras: {innings.Extras} (b {innings.Byes}, lb {innings.LegByes}, w {innings.Wides}, nb {innings.NoBalls})")
                    .FontSize(9).FontColor(Colors.Grey.Darken1);

                if (innings.Bowling.Any())
                {
                    col.Item().PaddingTop(4).Text("Bowling").Bold().FontSize(10);
                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(c =>
                        {
                            c.RelativeColumn(3);
                            c.RelativeColumn(1);
                            c.RelativeColumn(1);
                            c.RelativeColumn(1);
                            c.RelativeColumn(1);
                            c.RelativeColumn(1);
                        });

                        table.Header(header =>
                        {
                            foreach (var h in new[] { "Bowler", "O", "R", "W", "M", "Econ" })
                                header.Cell().Element(HeaderCell).Text(h).Bold();
                        });

                        foreach (var bw in innings.Bowling)
                        {
                            table.Cell().Element(BodyCell).Text(bw.PlayerName);
                            table.Cell().Element(BodyCell).Text(bw.OversText);
                            table.Cell().Element(BodyCell).Text(bw.RunsGiven.ToString());
                            table.Cell().Element(BodyCell).Text(bw.Wickets.ToString());
                            table.Cell().Element(BodyCell).Text(bw.Maidens.ToString());
                            table.Cell().Element(BodyCell).Text(bw.Economy.ToString("0.00"));
                        }
                    });
                }

                if (innings.FallOfWickets.Any())
                {
                    col.Item().PaddingTop(4).Text("Fall of Wickets").Bold().FontSize(10);
                    col.Item().Text(string.Join("   ",
                        innings.FallOfWickets.Select(w => $"{w.WicketNumber}-{w.TeamScoreAtFall} ({w.PlayerName}, {w.OverText})")))
                        .FontSize(9);
                }
            });
        }

        private static QuestPDF.Infrastructure.IContainer HeaderCell(QuestPDF.Infrastructure.IContainer c) =>
            c.Background(Colors.Grey.Lighten2).Padding(4);

        private static QuestPDF.Infrastructure.IContainer BodyCell(QuestPDF.Infrastructure.IContainer c) =>
            c.BorderBottom(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(4);
    }
}
