// <auto-generated />
using System;
using KplTournament.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KplTournament.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411103945_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("KplTournament.Web.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("KplTournament.Web.Models.BallByBall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BallNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BallResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BatsmanId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BowlerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtraRuns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Innings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBye")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLegBye")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNoBall")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWicket")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWide")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OverNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Runs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BatsmanId");

                    b.HasIndex("BowlerId");

                    b.HasIndex("MatchId");

                    b.ToTable("BallByBalls");
                });

            modelBuilder.Entity("KplTournament.Web.Models.BattingScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Balls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fours")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Runs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sixes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("BattingScores");
                });

            modelBuilder.Entity("KplTournament.Web.Models.BowlingScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Maidens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Overs")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunsGiven")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wickets")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("BowlingScores");
                });

            modelBuilder.Entity("KplTournament.Web.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentBall")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentBowlerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentInnings")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentOver")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentRuns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentWickets")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManOfTheMatchPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NonStrikerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OversPerInnings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StrikerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Target")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamAId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TeamAOvers")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamAScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamAWickets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamBId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TeamBOvers")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamBScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamBWickets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TossDecision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TossWinner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WinnerTeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrentBowlerId");

                    b.HasIndex("ManOfTheMatchPlayerId");

                    b.HasIndex("NonStrikerId");

                    b.HasIndex("StrikerId");

                    b.HasIndex("TeamAId");

                    b.HasIndex("TeamBId");

                    b.HasIndex("WinnerTeamId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("KplTournament.Web.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCaptain")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInjured")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsViceCaptain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("KplTournament.Web.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("KplTournament.Web.Models.BallByBall", b =>
                {
                    b.HasOne("KplTournament.Web.Models.Player", "Batsman")
                        .WithMany()
                        .HasForeignKey("BatsmanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KplTournament.Web.Models.Player", "Bowler")
                        .WithMany()
                        .HasForeignKey("BowlerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KplTournament.Web.Models.Match", "Match")
                        .WithMany("BallByBalls")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batsman");

                    b.Navigation("Bowler");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("KplTournament.Web.Models.BattingScore", b =>
                {
                    b.HasOne("KplTournament.Web.Models.Match", "Match")
                        .WithMany("BattingScores")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KplTournament.Web.Models.Player", "Player")
                        .WithMany("BattingScores")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KplTournament.Web.Models.Team", "Team")
                        .WithMany("BattingScores")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("KplTournament.Web.Models.BowlingScore", b =>
                {
                    b.HasOne("KplTournament.Web.Models.Match", "Match")
                        .WithMany("BowlingScores")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KplTournament.Web.Models.Player", "Player")
                        .WithMany("BowlingScores")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KplTournament.Web.Models.Team", "Team")
                        .WithMany("BowlingScores")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("KplTournament.Web.Models.Match", b =>
                {
                    b.HasOne("KplTournament.Web.Models.Player", "CurrentBowler")
                        .WithMany()
                        .HasForeignKey("CurrentBowlerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KplTournament.Web.Models.Player", "ManOfTheMatchPlayer")
                        .WithMany()
                        .HasForeignKey("ManOfTheMatchPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KplTournament.Web.Models.Player", "NonStriker")
                        .WithMany()
                        .HasForeignKey("NonStrikerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KplTournament.Web.Models.Player", "Striker")
                        .WithMany()
                        .HasForeignKey("StrikerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KplTournament.Web.Models.Team", "TeamA")
                        .WithMany()
                        .HasForeignKey("TeamAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KplTournament.Web.Models.Team", "TeamB")
                        .WithMany()
                        .HasForeignKey("TeamBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KplTournament.Web.Models.Team", "WinnerTeam")
                        .WithMany()
                        .HasForeignKey("WinnerTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentBowler");

                    b.Navigation("ManOfTheMatchPlayer");

                    b.Navigation("NonStriker");

                    b.Navigation("Striker");

                    b.Navigation("TeamA");

                    b.Navigation("TeamB");

                    b.Navigation("WinnerTeam");
                });

            modelBuilder.Entity("KplTournament.Web.Models.Player", b =>
                {
                    b.HasOne("KplTournament.Web.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("KplTournament.Web.Models.Match", b =>
                {
                    b.Navigation("BallByBalls");

                    b.Navigation("BattingScores");

                    b.Navigation("BowlingScores");
                });

            modelBuilder.Entity("KplTournament.Web.Models.Player", b =>
                {
                    b.Navigation("BattingScores");

                    b.Navigation("BowlingScores");
                });

            modelBuilder.Entity("KplTournament.Web.Models.Team", b =>
                {
                    b.Navigation("BattingScores");

                    b.Navigation("BowlingScores");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
